/**
 * 環境変数development
 */
export const environment = {
    production: false,
    APP_PREFIX: 'CI',
    PROJECT_ID: 'cinerino',
    ENV: 'development',
    ENTRANCE_SERVER_URL: '',
    WAITER_SERVER_URL: 'https://waiter-development.appspot.com',
    VIEW_TYPE: 'cinema',
    ANALYTICS_ID: '',
    STORAGE_NAME: 'CINERINO-FRONTEND-STATE',
    STORAGE_TYPE: 'sessionStorage',
    BASE_URL: '/purchase/root',
    LANGUAGE: ['ja', 'en'],
    PORTAL_SITE_URL: '',
    DISPLAY_TICKETED_SEAT: true,
    HEADER_MENU: true,
    HEADER_MENU_SCOPE: ['purchase', 'inquiry', 'order', 'mypage', 'setting', 'auth'],
    FOOTER_COMPANY_URL: 'https://motionpicture.jp',
    FOOTER_LAW_URL: 'https://motionpicture.jp',
    FOOTER_PRIVACY_POLICY_URL: 'https://motionpicture.jp',
    PURCHASE_CART_MAX_LENGTH: '1',
    PURCHASE_TRANSACTION_TIME: '15',
    PURCHASE_PRE_SCHEDULE_DATE: '3',
    PURCHASE_SCHEDULE_DEFAULT_SELECTED_DATE: '0',
    PURCHASE_SCHEDULE_DISPLAY_LENGTH: '10',
    PURCHASE_SCHEDULE_STATUS_WINDOW_TIME_MINUTES: '-20',
    PURCHASE_SCHEDULE_STATUS_THRESHOLD_VALUE: '30',
    PURCHASE_SCHEDULE_STATUS_THRESHOLD_UNIT: '%',
    INQUIRY_CANCEL: true,
    INQUIRY_QRCODE: true,
    INQUIRY_PRINT: true,
    PRINT_QR_CODE_TYPE: 'token'
};
